# This is a complete configuration to deploy Loki backed by the filesystem.
# The index will be shipped to the storage via tsdb-shipper.

auth_enabled: false

server:
  http_listen_port: 3100
  # HTTP API для приема данных от Promtail будет слушать на этом порту

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
    - from: 2020-05-15
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /tmp/loki/chunks  # Путь для хранения чанков логов
  boltdb_shipper:
    active_index_directory: /tmp/loki/index  # Путь для хранения индексов
    cache_location: /tmp/loki/cache  # Путь для кэширования индексов

# Конфигурация для работы с Promtail
# Примечание: Здесь не нужно никаких дополнительных настроек для Promtail, так как Promtail будет просто отправлять логи в Loki через HTTP API.
# Promtail будет работать по умолчанию с настройками, указанными в /loki/api/v1/push.
