include:
  - docker-compose.grafana.yaml

services:
  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - infrastructure_network
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
      - ./ssh_keys:./ssh_keys
      - ./authorized_keys:./authorized_keys
    networks:
      - infrastructure_network


networks:
   infrastructure_network:
    external: true